
=head1 NAME

HTML::Template::Ex::Filter - tmpl_tag filter for HTML::Template::Ex.

=head1 SYNOPSIS

  use HTML::Template::Ex;
  use HTML::Template::Ex::Filter;
  
  my $tmpl= HTML::Template::Ex->new(
    ...
    filter=> HTML::Template::Ex::Filter->set,
    );

  [%... include_template.tmpl %]
  
  [% ex %]
    my($self, $param)= @_;
    ...
    ..... ban, bo, bon.
    "";
  [% end_ex %]
  
  [% =param_name %]
  
  [% loop loop_param_name %]
    ...
  [% end_loop %]

=head1 DESCRIPTION

このモジュールは HTML::Template の書式を少し簡単にする為のフィルターを提供します。

=head1 TAGS

=head2 [% ex %] ... [% end_ex %]

<TMPL_EX> ... </TMPL_EX> に相当します。

NAME 属性を指定するには次のようにします。

  [% ex param_name %] ...

更に ESCAPE 属性は : で区切って次のように

  [% ex html:param_name %]

NAME 属性未指定の ESCAPE 属性は 先頭を : にして次のように

  [% ex html: %]

=head2 [% set PARAM_NAME="PARAM_VALUE" %]

<TMPL_SET NAME="PARAM_NAME" VALUE="PARAM_VALUE"> に相当します。

=head2 [% =VAR_NAME %]

<TMPL_VAR NAME="VAR_NAME"> に相当します。

ESCAPE属性は次のようにします。

  [% =html:VAR_NAME %]

=head2 [% if VAR_NAME %] ... [% else %] ... [% end_if %]

<TMPL_IF NAME="VAR_NAME"> ... <TMPL_ELSE> ... </TMPL_IF> に相当します。

=head2 [% unless VAR_NAME %] ... [% else %] ... [% end_unless %]

<TMPL_UNLESS NAME="VAR_NAME"> ... <TMPL_ELSE> ... </TMPL_UNLESS> に相当します。

=head2 [% loop ARRAY_NAME %] ... [% end_loop %]

<TMPL_LOOP NAME="ARRAY_NAME"> ... </TMPL_LOOP> に相当します。

=head2 [%... INCLUDE_TEMPLATE %]  or  [% include INCLUDE_TEMPLATE %]

<TMPL_INCLUDE NAME="..."> に相当します。

=head2 [% ! COMMENT_STRING %]  or [% comment COMMENT_STRING %]

コメントです。テンプレートには反映されません。

=head1 SEE ALSO

L<Egg::Release>,

=head1 AUTHOR

Masatoshi Mizuno E<lt>mizunoE<64>bomcity.comE<gt>

=head1 COPYRIGHT

Copyright (C) 2007 by Bee Flag, Corp. E<lt>L<http://egg.bomcity.com/>E<gt>, All Rights Reserved.

This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself, either Perl version 5.8.6 or,
at your option, any later version of Perl 5 you may have available.

=cut
